# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: neurosynth

dependencies:
  - python=2.7

  - pip:
    - numpy
    - pandas
    - nibabel
    - ply
    - scikit-learn
